<?php
/**
 * @category Mageants ExtraFee
 * @package Mageants_ExtraFee
 * @copyright Copyright (c) 2017 Mageants
 * @author Mageants Team <support@mageants.com>
 */
?>
<?php
/**
 * @see \Magento\Sales\Block\Adminhtml\Items\Column\Name
 */
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$model = $objectManager->create('Mageants\ExtraFee\Model\ExtraFee');
$priceHelper = $objectManager->create('Magento\Framework\Pricing\Helper\Data');
$productRepository = $objectManager->create('Magento\Catalog\Model\ProductRepository');
if ($_item = $block->getItem()):  ?>
    <div id="order_item_<?=  /* @escapeNotVerified */  $_item->getId() ?>_title"
         class="product-title">
        <?= $block->escapeHtml($_item->getName()) ?>
        
    </div>

    <div class="product-sku-block">
        <span><?=  /* @escapeNotVerified */  __('SKU') ?>:</span> <?= implode('<br />', $this->helper('Magento\Catalog\Helper\Data')->splitSku($block->escapeHtml($block->getSku()))); ?>
    </div>
    <?php $feesIds=$_item->getBuyRequest()->getFeesname();
    if (empty($feesIds)) {
        $productId = $_item->getProductId();
        $product=$productRepository->getById($productId);
        $overrideCat=$product->getOverrideCat();
        if ($overrideCat=="Yes") {
            $ExtraFeeList=$product->getExtrafeelist();
            $feeIds=explode(",", $ExtraFeeList);
            $ExtraFeeCollection=$model->getCollection()
                ->addFieldToSelect('id')
                ->addFieldToFilter('estatus', 'Enabled')
                ->addFieldToFilter('is_mandatory', 'Yes')
                ->addFieldToFilter('apply_to', [
                        ['finset'=> 'Product']
                    ])
                ->addFieldToFilter('id', ['in' => $feeIds]);
             $feesIds=$ExtraFeeCollection->getData();
        } elseif ($overrideCat=="No") {
            $ExtraFeeCollection=$model->getCollection()
                ->addFieldToSelect('id')
                ->addFieldToFilter('estatus', 'Enabled')
                ->addFieldToFilter('is_mandatory', 'Yes')
                ->addFieldToFilter('apply_to', [
                        ['finset'=> 'Category']
                    ]);

             $feesIds=$ExtraFeeCollection->getData();
        } else {
            $ExtraFeeList=$product->getExtrafeelist();
            $feeIds=explode(",", $ExtraFeeList);
            $categoryId=$product->getCategoryIds();
            $ExtraFeeCatIdCollection=$model->getCollection()
                ->addFieldToSelect('id')
                ->addFieldToSelect('category_ids')
                ->addFieldToFilter('estatus', 'Enabled')
                ->addFieldToFilter('is_mandatory', 'Yes')
                ->addFieldToFilter('apply_to', 'Category');
            $ExtraFeeCatCollection=$model->getCollection()
                ->addFieldToSelect('id')
                ->addFieldToFilter('estatus', 'Enabled')
                ->addFieldToFilter('is_mandatory', 'Yes')
                ->addFieldToFilter('apply_to', 'Category');
            $ExtraFeePrdCollection=$model->getCollection()
                ->addFieldToSelect('id')
                ->addFieldToFilter('estatus', 'Enabled')
                ->addFieldToFilter('is_mandatory', 'Yes')
                ->addFieldToFilter('apply_to', 'Product')
                ->addFieldToFilter('id', ['in' => $feeIds]);

            $ExtraCatFee=[];
            $ExtraPrdFee=[];
                    
            if (sizeof($ExtraFeeCatCollection) > 0) {
                      $data = $ExtraFeeCatIdCollection->getData();
                      $result = [];
                foreach ($data as $datas) {
                    $feeCatId = explode(",", $datas['category_ids']);
                    $result=array_intersect($feeCatId, $categoryId);
                            
                    if (sizeof($result) > 0) {
                               $ExtraCatFee=$ExtraFeeCatCollection->getData();
                    }
                }
            }
            if (sizeof($ExtraFeePrdCollection) > 0) {
                       $ExtraPrdFee=$ExtraFeePrdCollection->getData();
            }
                            $feesIds=array_merge($ExtraCatFee, $ExtraPrdFee);
        }
    }
            $price=$_item->getPrice();
    if (sizeof($feesIds)>0) { ?>
                <div class="extrafee-option">
                <?php foreach ($feesIds as $fee) {
                    $feeData=$model->load($fee)->getData(); ?>
                <br/>
                <span class="feesname"><?= __($feeData['feesname']); ?></span>: <span><?php if ($feeData['type']=='Percentage') {
                    $amount=(($price*$feeData['amount'])/100);
                    echo $priceHelper->currency($amount, true, false);
                                       } else {echo $priceHelper->currency($feeData['amount'], true, false);} ?> </span>    
            <?php } ?>
                </div>
        <?php  } ?>

    <?php if ($block->getOrderOptions()): ?>
        <dl class="item-options">
            <?php foreach ($block->getOrderOptions() as $_option): ?>
                <dt><?=  /* @escapeNotVerified */  $_option['label'] ?>:</dt>
                <dd>
                    <?php if (isset($_option['custom_view']) && $_option['custom_view']): ?>
                        <?=  /* @escapeNotVerified */  $block->getCustomizedOptionValue($_option); ?>
                    <?php else: ?>
                        <?php $_option = $block->getFormattedOption($_option['value']); ?>
                        <?=  /* @escapeNotVerified */  $_option['value']; ?><?php if (isset($_option['remainder']) && $_option['remainder']): ?><span id="<?=  /* @escapeNotVerified */  $_dots = 'dots' . uniqid()?>"> ...</span><span id="<?=  /* @escapeNotVerified */  $_id = 'id' . uniqid()?>"><?=  /* @escapeNotVerified */  $_option['remainder'] ?></span>
                            <script>
                                require(['prototype'], function() {
                                    $('<?=  /* @escapeNotVerified */  $_id ?>').hide();
                                    $('<?=  /* @escapeNotVerified */  $_id ?>').up().observe('mouseover', function(){$('<?=  /* @escapeNotVerified */  $_id ?>').show();});
                                    $('<?=  /* @escapeNotVerified */  $_id ?>').up().observe('mouseover', function(){$('<?=  /* @escapeNotVerified */  $_dots?>').hide();});
                                    $('<?=  /* @escapeNotVerified */  $_id ?>').up().observe('mouseout',  function(){$('<?=  /* @escapeNotVerified */  $_id ?>').hide();});
                                    $('<?=  /* @escapeNotVerified */  $_id ?>').up().observe('mouseout',  function(){$('<?=  /* @escapeNotVerified */  $_dots ?>').show();});
                                });
                            </script>
                        <?php endif; ?>
                    <?php endif; ?>
                </dd>
            <?php endforeach; ?>
        </dl>
    <?php endif; ?>
    <?= $block->escapeHtml($_item->getDescription()) ?>
<?php endif; ?>
