<?php
/**
 * @category Mageants ImageGallery
 * @package Mageants_ImageGallery
 * @copyright Copyright (c) 2017 Mageants
 * @author Mageants Team <support@mageants.com>
 */

$helper=$this->helper('Mageants\ImageGallery\Helper\Data');
$id = $block->getRequest()->getParam('category_id');
$collection = $helper->getCategoryById($id);
$headerTitle = '';
if (count($collection->getData()) >= 1) {
    $collection = $collection->getData();
    $headerTitle = $collection[0]['category_name'];
}?>
<div class="page-title"><span><h3 style="background-color: <?=$helper->getHeaderBgColor();?>; color:<?=$helper->getHeaderForeColor();?>;"><?php echo __($headerTitle); ?></h3></span></div>
<div class="gallery-action">
<a id="back" style="display:block"><?php echo __("Back")?></a>
<a class="images_gallery_button" id="<?= $id;?>" style="display:block"><?php echo __("Images")?></a>
<a class="videos_gallery_button" id="<?= $id;?>" style="display:block;"><?php echo __("Videos")?></a>
</div>
<div id="images_gallery">
<div class="zoom-gallery">    
    <div id="mygallery">
        <?php
        if ($block->getRequest()->getParam('category_id')) {
            $Id=$block->getRequest()->getParam('category_id');
            $helper=$this->helper('Mageants\ImageGallery\Helper\Data');
            $collection=$helper->getCategoryById($Id);
            if ($collection) {
                foreach ($collection as $category) {
                    if (!empty($category['image_id'])) {
                            
                        $imageids=$helper->getCategorieImageIds($category['category_id']);
                        
                        foreach ($imageids as $imageid) {
                            if ($helper->getGalleryImageUrl($imageid)) { ?>
                                <?php $result=$helper->getGalleryImageUrl($imageid);
                                ?>
                                <a href="<?php echo $result['url'] ; ?>" data-source="<?php echo $result['url'] ; ?>" title="<?php echo $result['title'] ; ?>" style="width:193px;height:125px;">
                                    <img src="<?php echo $result['url'] ; ?>" width="193" height="125">
                                </a>                    
                    <?php	}
                        }
                    } else {
                        echo __("Sorry !! We don't have any selected Images for this image gallery");
                    }
                }
            }?>
            <br/>
        <?php } ?>    
    </div>
</div>
</div>
<div id="gallery_image" class="displayval">
    <?php $url = '' ?>
    <?php $collection=$helper->getCategories();
    
    if (sizeof($collection) > 0) {
        foreach ($collection as $category) {
            $categoryid=$category['category_id'];
            $url = preg_replace('#[^0-9a-z]+#i', '-', $category['url_key']);
            $url = $this->getBaseUrl()."imagegallery/".$url.".html";

            ?>
            <div class="uniq">
                <a id="<?php echo $category['category_id']; ?>">    
                    <img id="image_id" src='<?php echo $helper->getCategoryImageUrl($categoryid); ?>' alt='' width="300" />
                </a>
                <input type="hidden" class="category_url" value="<?=$url?>" />
                <h2><a id="<?php echo $category['category_id']; ?>" href="javascript:void(0)">    <?php echo $category['category_name']; ?></a>
                    <input type="hidden" class="category_url" value="<?=$url?>" />
                </h2>
            </div>
            <?php
        }
    } else {
        echo 'No Image Category Found';
    }?>
</div>
<div class="loader"></div>
<div id="myModal" class="modal" style="display:none">
    <img class="modal-content zoomIn animated" id="imagegallery">    
</div>    
<script type="text/javascript">
    require(['jquery'],function($){
        $(document).ready(function(){
            var imageUrl="<?php echo $block->getViewFileUrl('Mageants_ImageGallery::images/hour.gif'); ?>";
            $('.loader').css({'background':'url(' + imageUrl + ') 50% 50% no-repeat rgb(249,249,249)','display':'none'});
            $('#back').click(function() {
                $('.page-title span h3').text("<?php echo __("Image Gallery"); ?>");
                $('#images_gallery').html('');
                $('#gallery_image').removeClass('displayval');
                $(this).css("display","none");
                $('.images_gallery_button').css("display","none");
                $('.videos_gallery_button').css("display","none");
                $url = '<?php echo $this->getBaseUrl()."imagegallery/"; ?>';
                window.location.href = $url;    
            });

            $('.images_gallery_button').click(function() {
                var id = $(this).attr('id');
                $('.loader').css("display","block");
                $.ajax({
                    type: 'POST',
                    url: '<?php echo $this->getUrl('imagegallery/index/index'); ?>',
                    data: { categoryid: id},
                    success: function(response) {
                        $('#images_gallery').html(response);
                    },
                    complete: function(){
                        $('.loader').css("display","none");
                    }
                });
            });

            $('.videos_gallery_button').click(function() {
                var id = $(this).attr('id');
                $('.loader').css("display","block");
                $.ajax({
                    type: 'POST',
                    url: '<?php echo $this->getUrl('imagegallery/index/videos'); ?>',
                    data: { categoryid: id},
                    success: function(response) {
                        $('#images_gallery').html(response);
                    },
                    complete: function(){
                        $('.loader').css("display","none");
                    }
                });
            });        
        });
        
        
    });
</script>    
<script type="text/javascript">
    require(['jquery','jquery/ui','justifiedGallery','magnificpopup'],function(jQuery){
        jQuery(document).ready(function(){
            jQuery("#mygallery").justifiedGallery({
                margins : 8
            });
            jQuery('.zoom-gallery').magnificPopup({
                delegate: 'a',
                type: 'image',
                closeOnContentClick: false,
                closeBtnInside: false,
                mainClass: 'mfp-with-zoom mfp-img-mobile',
                image: {
                    verticalFit: true,
                    titleSrc: function(item) {
                        return item.el.attr('title') + ' &middot; <a class="image-source-link" href="'+item.el.attr('data-source')+'" target="_blank">image source</a>';
                    }
                },
                gallery: {
                    enabled: true
                },
                zoom: {
                    enabled: true,
                    duration: 300, // don't foget to change the duration also in CSS
                    opener: function(element) {
                        return element.find('img');
                    }
                }
                
            });
            
        });    
    });
</script>