<script type="text/javascript">
    require(['jquery','justifiedGallery','magnificpopup'],function($){
        $(document).ready(function(){
            $('.popup-youtube, .popup-vimeo, .popup-gmaps').magnificPopup({
                disableOn: 700,
                type: 'iframe',
                mainClass: 'mfp-fade',
                removalDelay: 160,
                preloader: false,
                fixedContentPos: false,
                enableEscapeKey: true 
               });    
            
        });    
    });
</script>
<div class="zoom-gallery">    
    <div id="mygallery" class="video-gallery">
        <?php
        // filter_input(INPUT_POST, 'categoryid')
        // if (isset($_POST['categoryid'])) {
            // $Id=$_POST['categoryid'];
        if (filter_input(INPUT_POST, 'categoryid')) {
            $Id=filter_input(INPUT_POST, 'categoryid');
            $helper=$this->helper('Mageants\ImageGallery\Helper\Data');
            $collection=$helper->getCategoryById($Id);
            if ($collection) {
                foreach ($collection as $category) {
                    if (!empty($category['video_id'])) {
                            
                        $videoids=$helper->getCategorieVideoIds($category['category_id']);
                            
                        foreach ($videoids as $videoId) {
                            if ($helper->getGalleryVideoUrl($videoId)) { ?>
                                <?php $result=$helper->getGalleryVideoUrl($videoId);
                                ?>
                                <div class="video-list">
                                    <a class="popup-youtube" href="<?php echo $result['url'] ; ?>" data-source="<?php echo $result['url'] ; ?>" title="<?php echo $result['title'] ; ?>">
                                        <video controls>
                                              <source src="<?php echo $result['url'] ; ?>" type="video/mp4">
                                              <source src="mov_bbb.ogg" type="video/ogg">
                                          Your browser does not support HTML5 video.
                                        </video>
                                        <span><?php echo $result['title'] ; ?></span>
                                    </a>
                                </div>                    
                    <?php	}
                        }
                    } else { ?>
                            <span class="error-msg"><?= __("Sorry !! We don't have any selected Videos for this video gallery.");?></span>
                        <?php }
                }
            }
        } ?>    
    </div>
</div>

    
