<?php
/**
 * @category Mageants PreOrder
 * @package Mageants_PreOrder
 * @copyright Copyright (c) 2018  Mageants
 * @author Mageants Team <support@mageants.com>
 */
?>
<?php $blockObj= $block->getLayout()->createBlock('Mageants\PreOrder\Block\Preorder'); ?>
<?php $block->setPreconfiguredValue(); ?>
<?php $_product = $block->getProduct(); ?>
<?php $_associatedProducts = $block->getAssociatedProducts(); ?>
<?php $_hasAssociatedProducts = count($_associatedProducts) > 0; ?>

<div class="table-wrapper grouped">
    <table class="table data grouped" id="super-product-table">
        <caption class="table-caption"><?= /* @escapeNotVerified */ __('Grouped product items') ?></caption>
        <thead>
        <tr>
            <th class="col item" scope="col"><?= /* @escapeNotVerified */ __('Product Name') ?></th>
            <?php if ($_product->isSaleable()): ?>
                <th class="col qty" scope="col"><?= /* @escapeNotVerified */ __('Qty') ?></th>
            <?php endif; ?>
        </tr>
        </thead>

        <?php if ($_hasAssociatedProducts): ?>
            <?php foreach ($_associatedProducts as $_item): ?>
        <tbody>
            <tr>
                <td data-th="<?= $block->escapeHtml(__('Product Name')) ?>" class="col item">
                    <strong class="product-item-name"><?= $block->escapeHtml($_item->getName()) ?></strong>
                    <?php if ($block->getCanShowProductPrice($_product)): ?>
                        <?php if ($block->getCanShowProductPrice($_item)): ?>
                            <?= /* @escapeNotVerified */ $block->getProductPrice($_item) ?>
                        <?php endif; ?>
                     <?php endif; ?>
                     <?php
                        $preorderstock = $blockObj->getProductStockStatusById($_item->getId());
                        if ($blockObj->getACTIVE()) {
                            $pre_order_message = "";
                            if ($preorderstock->getPreorderNote() !="") {
                                $pre_order_message = $preorderstock->getPreorderNote();
                            } else {
                                $pre_order_message = $blockObj->getDefaultMessageForPreorder();
                            }
                            if ($preorderstock->getBackorders() == 4) {
                                if ($preorderstock->getBackstockPreorders() == 1) { ?>
                                    <div class="preorder_note">
                                    <div class="preorder_info"><?php echo $pre_order_message ?></div>
                                    <?php if ($preorderstock->getPreorderAvailabilityDate() != "") { ?>
                                            <div class="preorder_date"><span>Available On :: </span><?php echo $preorderstock->getPreorderAvailabilityDate(); ?>
                                            </div>
                                    <?php } ?>
                                    </div>
                               <?php } elseif ($preorderstock->getBackstockPreorders() == 0) {
                                    // if($blockObj->getAlloweOutofproduct()){ ?>
                                       <div class="preorder_note">
                                        <div class="preorder_info"><?php echo $pre_order_message ?></div>
                                        <?php if ($preorderstock->getPreorderAvailabilityDate() != "") { ?>
                                            <div class="preorder_date"><span>Available On :: </span><?php echo $preorderstock->getPreorderAvailabilityDate(); ?>
                                            </div>
                                        <?php } ?>
                                        </div>
                                    <?php //}
                               }
                            }
                        }
                        
                        ?>
                </td>
                <?php if ($_product->isSaleable()): ?>
                <td data-th="<?= $block->escapeHtml(__('Qty')) ?>" class="col qty">
                    <?php if ($_item->isSaleable()): ?>
                    <div class="control qty">
                        <input type="number"
                               name="super_group[<?= /* @escapeNotVerified */ $_item->getId() ?>]"
                               data-selector="super_group[<?= /* @escapeNotVerified */ $_item->getId() ?>]"
                               value="<?= /* @escapeNotVerified */ $_item->getQty() * 1 ?>"
                               title="<?= /* @escapeNotVerified */ __('Qty') ?>"
                               class="input-text qty"
                               data-validate="{'validate-grouped-qty':'#super-product-table'}"
                               data-errors-message-box="#validation-message-box"/>
                    </div>
                <?php else: ?>
                    <div class="stock unavailable" title="<?= /* @escapeNotVerified */ __('Availability') ?>">
                        <span><?= /* @escapeNotVerified */ __('Out of stock') ?></span>
                    </div>
                <?php endif; ?>
                </td>
                <?php endif; ?>
            </tr>
                <?php if ($block->getCanShowProductPrice($_product)
                && $block->getCanShowProductPrice($_item)
                && trim($block->getProductPriceHtml(
                    $_item,
                    \Magento\Catalog\Pricing\Price\TierPrice::PRICE_CODE
                ))): ?>
                <tr class="row-tier-price">
                    <td colspan="2">
                        <?= $block->getProductPriceHtml(
                            $_item,
                            \Magento\Catalog\Pricing\Price\TierPrice::PRICE_CODE
                        ) ?>
                    </td>
                </tr>
            <?php endif; ?>
        </tbody>
        <?php endforeach; ?>
        <?php else: ?>
        <tbody>
            <tr>
                <td class="unavailable"
                    colspan="<?php if ($_product->isSaleable()): ?>4<?php else: ?>3<?php endif; ?>">
                    <?= /* @escapeNotVerified */ __('No options of this product are available.') ?>
                </td>
            </tr>
        </tbody>
        <?php endif; ?>
    </table>
</div>
<div id="validation-message-box"></div>
