<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php //$_source  = $block->getSource()

?>
<tr>
    <td class="label"><div id="store_credit_return_amount">Store Credit</div></td>
    <td>
        <input type="text"
               name="creditmemo[store_credit_return_amount]"
               value="<?= '44' ?>"
               class="input-text admin__control-text not-negative-amount"
               id="store_credit_amount" />
    </td>
</tr>
