<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * Grouped product data template
 *
 * @var $block \Magento\Catalog\Block\Product\View\BaseImage
 * @var $block \Magento\GroupedProduct\Block\Product\View\Type\Grouped
 */
?>
<?php $block->setPreconfiguredValue(); ?>
<?php $_product = $block->getProduct(); ?>
<?php $_associatedProducts = $block->getAssociatedProducts(); ?>
<?php $_hasAssociatedProducts = count($_associatedProducts) > 0; ?>
<?php $notifyBlock= $block->getLayout()->createBlock('Mageants\OutofStockNotification\Block\Product\Notify'); ?>

<div class="table-wrapper grouped">
    <table class="table data grouped"
           id="super-product-table"
           data-mage-init='{ "Magento_GroupedProduct/js/product-ids-resolver": {} }'>
        <caption class="table-caption"><?= $block->escapeHtml(__('Grouped product items')) ?></caption>
        <thead>
        <tr>
            <th class="col item" scope="col"><?= $block->escapeHtml(__('Product Name')) ?></th>
            <?php if ($_product->isSaleable()) : ?>
                <th class="col qty" scope="col"><?= $block->escapeHtml(__('Qty')) ?></th>
            <?php endif; ?>
        </tr>
        </thead>

        <?php if ($_hasAssociatedProducts) : ?>
        <tbody>
            <?php foreach ($_associatedProducts as $_item) : ?>
            <tr>
                <td data-th="<?= $block->escapeHtmlAttr(__('Product Name')) ?>" class="col item">
                    <strong class="product-item-name"><?= $block->escapeHtml($_item->getName()) ?></strong>
                    <?php if ($block->getCanShowProductPrice($_product)) : ?>
                        <?php if ($block->getCanShowProductPrice($_item)) : ?>
                            <?= /* @noEscape */ $block->getProductPrice($_item) ?>
                        <?php endif; ?>
                        <?php endif; ?>
                </td>
                <?php 
                      $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
                      $inventory = $objectManager->create('\Magento\CatalogInventory\Model\Stock\StockItemRepository');
                      $stockInventor =$inventory->get($_item->getId());
                ?>
                <?php if ($_product->isSaleable()) : ?>
                <td data-th="<?= $block->escapeHtmlAttr(__('Qty')) ?>" class="col qty">
                    <?php if ($_item->isSaleable()) : ?>
                    <div class="control qty">
                        <input type="number"
                               name="super_group[<?= $block->escapeHtmlAttr($_item->getId()) ?>]"
                               data-selector="super_group[<?= $block->escapeHtmlAttr($_item->getId()) ?>]"
                               value="<?= $block->escapeHtmlAttr($_item->getQty() * 1) ?>"
                               title="<?= $block->escapeHtmlAttr(__('Qty')) ?>"
                               class="input-text qty"
                               data-validate="{'validate-grouped-qty':'#super-product-table'}"
                               data-errors-message-box="#validation-message-box"/>
                    </div>
                <?php else : ?>
                    <div class="stock unavailable" title="<?= $block->escapeHtmlAttr(__('Availability')) ?>">
                        <span><?= $block->escapeHtml(__('Out of stock')) ?></span>
                    </div>
                <?php endif; ?>
                </td>
                <?php endif; ?>
            </tr>
            <?php if (!$stockInventor->getIsInStock() && $notifyBlock->isAllowCustomerGroup()) : ?>
                
            <tr>
                <td>
                    <div class="mageants-notify-main">
                        <div id="mageants-notify-form">
                            <div class="mageants-notify-group">
                                <div>
                                    <p><?php echo $notifyBlock->getNotificationMessage(); ?></p>
                                    <input type="hidden" id="customerId" name="customerId" value="<?php echo $notifyBlock->getLoggedCustomerId(); ?>">
                                    <input type="hidden" id="productSku" name="productSku" value="<?php echo $_item->getSku(); ?>">
                                    <input type="hidden" id="productName" name="productName" value="<?php echo $_item->getName(); ?>">
                                    <input type="hidden" name="producturl" class="producturl" value="<?php echo $_product->getUrlKey().'.html'; ?>">
                                </div>
                                <div>
                                    <div>
                                        <input type="email" id="notify" name="notify" placeholder="<?= __('Please enter your email id') ?>" value = "<?php if ($notifyBlock->isLoggedIn()) { echo trim($notifyBlock->getLoggedCustomerEmail()); } ?>">
                                    </div>
                                    <div class="mageants-notification" style="margin-top: 10px;">
                                        <button id="notifyGroup" class="action primary notifyGroup"  type="button" title="<?= __('Notify') ?>"><?= __('Notify') ?></button>
                                    </div>
                                </div>                                
                            </div>
                        </div>
                    </div>
                </td>
                <td>
                    <div class="control qty" style="display: none;">
                        <input type="number"
                               name="super_group[<?= $block->escapeHtmlAttr($_item->getId()) ?>]"
                               data-selector="super_group[<?= $block->escapeHtmlAttr($_item->getId()) ?>]"
                               value="<?= $block->escapeHtmlAttr($_item->getQty() * 1) ?>"
                               title="<?= $block->escapeHtmlAttr(__('Qty')) ?>"
                               class="input-text qty"
                               data-validate="{'validate-grouped-qty':'#super-product-table'}"
                               data-errors-message-box="#validation-message-box"/>
                    </div>
                </td>
            </tr>
            <!--  -->
            <?php endif; ?>
                <?php if ($block->getCanShowProductPrice($_product)
                && $block->getCanShowProductPrice($_item)
                && trim($block->getProductPriceHtml(
                    $_item,
                    \Magento\Catalog\Pricing\Price\TierPrice::PRICE_CODE
                ))) : ?>
                <tr class="row-tier-price">
                    <td colspan="2">
                        <?= $block->getProductPriceHtml(
                            $_item,
                            \Magento\Catalog\Pricing\Price\TierPrice::PRICE_CODE
                        ) ?>
                    </td>
                </tr>
            <?php endif; ?>
        <?php endforeach; ?>
        </tbody>
        <?php else : ?>
        <tbody>
            <tr>
                <td class="unavailable"
                    colspan="<?php if ($_product->isSaleable()) : ?>4<?php else : ?>3<?php endif; ?>">
                    <?= $block->escapeHtml(__('No options of this product are available.')) ?>
                </td>
            </tr>
        </tbody>
        <?php endif; ?>
    </table>
</div>
<div id="validation-message-box"></div>
<script type="text/javascript">
    require([
      'jquery',
      'jquery/ui'
    ], function($){
         $(document).ready(function() {
            $('.notifyGroup').on('click', function () {
                var body = $('body').loader();
                body.loader('show');
                var customerId = $(this).parents(".mageants-notify-group").find("#customerId").val();
                var productSku = $(this).parents(".mageants-notify-group").find("#productSku").val();
                var productName = $(this).parents(".mageants-notify-group").find("#productName").val();
                var customerEmail = $(this).parents(".mageants-notify-group").find("#notify").val();
                var producturl = $(this).parents(".mageants-notify-group").find(".producturl").val();
                $.ajax({
                    type: "POST",
                    url: "<?php echo $notifyBlock->getSaveUrl(); ?>",
                    data: {Id: customerId, Sku:productSku, Name:productName, Email:customerEmail, producturl:producturl},
                    success:  function(data){
                        window.location.reload(true);
                    }
                });    
            });
        });
    }); 
</script>
