<?php
/**
 * @category Mageants FreeShippingBar
 * @package Mageants_FreeShippingBar
 * @copyright Copyright (c) 2019 Mageants
 * @author Mageants Team <support@mageants.com>
 */ ?>
<div>
<div>
    <div class="freeshippingbar">
        <a class="link">
            <div class="content-shippingbar">
                <p class="first-message">Free Shipping for order over <span class="goal">{{goal}}</span></p>
            </div>
        </a>
    </div>
    <div class="freeshippingbar">
        <a class="link">
            <div class="content-shippingbar">
                <p class="first-message">Only <span class="goal">{{below_goal}}</span> away for free shipping
                </p>
            </div>
        </a>
    </div>
    <div class="freeshippingbar">
        <a class="link">
            <div class="content-shippingbar">
                <p class="first-message">Congrats! You have got free shipping </p>
            </div>
        </a>
    </div>
</div>
</div>
