<?php
/**
 * @category Mageants FastOrder
 * @package Mageants_FastOrder
 * @copyright Copyright (c) 2018 Mageants
 * @author Mageants Team <support@mageants.com>
 */
?>

<?php
$_option = $block->getOption();
$class = ($_option->getIsRequire()) ? ' required' : '';
?>
<div class="field<?php /* @escapeNotVerified */ echo $class; ?> mgantsoptions-info">
    <label class="label" for="select_<?php /* @escapeNotVerified */ echo $_option->getId() ?>">
        <span><?php echo  $block->escapeHtml($_option->getTitle()) ?></span>
    </label>
    <div class="control">
        <?php echo $block->getValuesHtml() ?>
        <?php if ($_option->getIsRequire()): ?>
            <?php if ($_option->getType() == \Magento\Catalog\Model\Product\Option::OPTION_TYPE_RADIO || $_option->getType() == \Magento\Catalog\Model\Product\Option::OPTION_TYPE_CHECKBOX): ?>
                <span id="mgantscustomoption-<?php /* @escapeNotVerified */ echo $_option->getId() ?>-container"></span>
            <?php endif; ?>
        <?php endif;?>
    </div>
</div>

<script type="text/javascript">
    require(['jquery', 'jquery/ui', 'jquery/jquery.cookie'], function($, ui, cookie){
        jQuery(document).ready( function() {
            var custom_selected_value = $.cookie('custom_selected_value');
            if (custom_selected_value) {
                var $this = $(this).find("#mgantscontent-option-product form#mgantsfastorder-form-option .mgantsproduct-option select");
                $($this).val(custom_selected_value).trigger('change');
                $($this).each(function(){
                    var option_val = $(this).val();
                    if (option_val == custom_selected_value) {
                        $(this).attr("selected","selected");
                    }
                })  
            }
        });
    });  
</script>